# FP-Kecerdasan-Buatan

## Import Library

In [1]:
import pandas as pd
import numpy as np

## Load Data Training

### Attribute Information:
1. Date : (DD/MM/YYYY) Day, month ('june' to 'september'), year (2012) Weather data observations
2. Temp : temperature noon (temperature max) in Celsius degrees: 22 to 42
3. RH : Relative Humidity in %: 21 to 90
4. Ws :Wind speed in km/h: 6 to 29
5. Rain: total day in mm: 0 to 16.8 FWI Components
6. Fine Fuel Moisture Code (FFMC) index from the FWI system: 28.6 to 92.5
7. Duff Moisture Code (DMC) index from the FWI system: 1.1 to 65.9
8. Drought Code (DC) index from the FWI system: 7 to 220.4
9. Initial Spread Index (ISI) index from the FWI system: 0 to 18.5
10. Buildup Index (BUI) index from the FWI system: 1.1 to 68
11. Fire Weather Index (FWI) Index: 0 to 31.1
12. Classes: two classes, namely fire and not fire

In [2]:
# Read fie csv
forest_df = pd.read_csv('./dataset/training.csv', header=[0])

# Drop kolom hari, bulan, dan tahun karena tidak dibutuhkan
clean_df = forest_df.drop(columns=["day", "month", "year"])
clean_df.head()

Temperature   RH   Ws  Rain   FFMC  DMC    DC  ISI  BUI  FWI      Classes
0           29   57   18    0.0  65.7  3.4   7.6  1.3  3.4  0.5  not fire   
1           29   61   13    1.3  64.4  4.1   7.6  1.0  3.9  0.4  not fire   
2           26   82   22   13.1  47.1  2.5   7.1  0.3  2.7  0.1  not fire   
3           25   89   13    2.5  28.6  1.3   6.9  0.0  1.7  0.0  not fire   
4           27   77   16    0.0  64.8  3.0  14.2  1.2  3.9  0.5  not fire

## Samples

In [3]:
batch_string = np.array(clean_df.drop(columns=['Classes']))

batch = []
for sample in batch_string:
    _ = []
    for attribute in sample:
        _.append(float(attribute))
    batch.append(_)

batch = np.array(batch)

print(batch)

[[29.  57.  18.  ...  1.3  3.4  0.5]
 [29.  61.  13.  ...  1.   3.9  0.4]
 [26.  82.  22.  ...  0.3  2.7  0.1]
 ...
 [27.  87.  29.  ...  0.4  3.4  0.2]
 [24.  54.  18.  ...  1.7  5.1  0.7]
 [24.  64.  15.  ...  1.2  4.8  0.5]]


## Classes

In [4]:
classes = np.array(clean_df['Classes'])

outputs = []
for item in classes:
    if(item.strip() == 'not fire'):
        outputs.append(0)
    elif(item.strip() == 'fire'):
        outputs.append(1)

y = np.array(outputs)

print(y)

[[1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [1]
 [1]
 [2]
 [2]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [1]
 [2]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [1]
 [1]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]


## Neural Networks

In [5]:
# Layer Class
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # Generate random weights
        self.weights = np.random.randn(n_inputs, n_neurons) / 100
        
        # Make array fill of zeros
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        # Keep input values
        self.inputs = inputs
        
        # dot product of input with weight plus bias
        self.output = np.dot(inputs, self.weights) + self.biases

    def backward(self, dvalues):
        # Get derivative value of weight and bias
        self.dweights = np.dot(self.inputs.T, dvalues)
        self.dbiases = np.sum(dvalues, axis=0, keepdims=True)
        
        # Get input derivative
        self.dinputs = np.dot(dvalues, self.weights.T)


# Activation Function ReLU Class
class Activation_ReLU:
    def forward(self, inputs):
        # Keep input values
        self.inputs = inputs
        
        # ReLU function
        self.output = np.maximum(0, inputs)

    def backward(self, dvalues):
        # copy dvalues
        self.dinputs = dvalues.copy()
        
        # if inputs <= 0 then make it 0
        self.dinputs[self.inputs <= 0] = 0


# Activation Softmax Class
class Activation_Softmax:
    def forward(self, inputs):
        # Eksponensial dan Prevent Overflow
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        
        # Normalisasi
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        
        # produce probabilites distribution
        self.output = probabilities

    def backward(self, dvalues):
        # Create uninitialized array
        self.dinputs = np.empty_like(dvalues)
        
        # Enumerate outputs and gradients
        for index, (single_output, single_dvalues) in enumerate(zip(self.output, dvalues)):
            # Flatten output array
            single_output = single_output.reshape(- 1, 1)
            
            # Calculate Jacobian matrix of the output and
            jacobian_matrix = np.diagflat(single_output) - np.dot(single_output, single_output.T)
            
            # Calculate sample-wise gradient
            # and add it to the array of sample gradients
            self.dinputs[index] = np.dot(jacobian_matrix, single_dvalues)


# Loss Class
class Loss:
    # Calculate loss
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        
        # Mean of losses
        data_loss = np.mean(sample_losses)
        return data_loss


# Categorical Cross Entropy Class
class Loss_CategoricalCrossentropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        
        # Clip to prevent -log(0) because it produces INF(infinite)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped * y_true, axis=1)

        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods

    def backward(self, dvalues, y_true):
        # Number of samples
        samples = len(dvalues)
        
        # Number of labels in every sample
        labels = len(dvalues[0])

        if len(y_true.shape) == 1:
            y_true = np.eye(labels)[y_true]

        # Calculate gradient
        self.dinputs = - y_true / dvalues
        
        # Normalize gradient
        self.dinputs = self.dinputs / samples


# Softmax classifier - combined Softmax activation
# and cross-entropy loss for faster backward step
class Activation_Softmax_Loss_CategoricalCrossentropy ():
    # Creates activation and loss function objects
    def __init__(self):
        self.activation = Activation_Softmax()
        self.loss = Loss_CategoricalCrossentropy()
        
    def forward(self, inputs, y_true):
        # Output layer's activation function
        self.activation.forward(inputs)
        
        # Set the output
        self.output = self.activation.output
        
        # Calculate and return loss value
        return self.loss.calculate(self.output, y_true)

    def backward(self, dvalues, y_true):
        # Number of samples
        samples = len(dvalues)
        
        # If labels are one-hot encoded,
        # turn them into discrete values
        if len(y_true.shape) == 2:
            y_true = np.argmax(y_true, axis=1)

        # Copy so we can safely modify
        self.dinputs = dvalues.copy()
        
        # Calculate gradient
        self.dinputs[range(samples), y_true] -= 1
        
        # Normalize gradient
        self.dinputs = self.dinputs / samples


# Sthocastic Gradient Descent
class Optimizer_SGD:
    # Initialize optimizer - set settings,
    # learning rate of 1. is default for this optimizer
    def __init__(self, learning_rate=1.0):
        self.learning_rate = learning_rate
        
    # Update parameters
    def update_params(self, layer):
        layer.weights += - self.learning_rate * layer.dweights
        layer.biases += - self.learning_rate * layer.dbiases

## Training NN

In [7]:
# Hidden Layer 1
dense1 = Layer_Dense(10, 64)
activation1 = Activation_ReLU()

# Hidden Layer 2
dense2 = Layer_Dense(64, 64)
activation2 = Activation_ReLU()

# Output Layer
dense3 = Layer_Dense(64, 2)

# loss and softmax activation
loss_activation = Activation_Softmax_Loss_CategoricalCrossentropy()

# Optimizer
optimizer = Optimizer_SGD(learning_rate=0.01)

# Training
for epoch in range(10001):
    dense1.forward(batch)
    activation1.forward(dense1.output)

    dense2.forward(activation1.output)
    activation2.forward(dense2.output)

    dense3.forward(activation2.output)

    loss = loss_activation.forward(dense3.output, y)

    preds = np.argmax(loss_activation.output, axis=1)

    if len(y.shape) == 2:
        y = np.argmax(y, axis=1)
    accuracy = np.mean(preds == y)

    if not epoch % 100:
        print(f'epoch: {epoch}, acc: {accuracy}, loss: {loss}')
        
    # Backpropagation
    loss_activation.backward(loss_activation.output, y)
    dense3.backward(loss_activation.dinputs)
    activation2.backward(dense3.dinputs)
    dense2.backward(activation2.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    # Update weights and biases
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    optimizer.update_params(dense3)

epoch: 0, acc: 0.9631147540983607, loss: 0.6920619987753959
epoch: 100, acc: 1.0, loss: 0.0021185921409403135
epoch: 200, acc: 1.0, loss: 0.000718985059005452
epoch: 300, acc: 1.0, loss: 0.00040894981697428974
epoch: 400, acc: 1.0, loss: 0.0002790384272991017
epoch: 500, acc: 1.0, loss: 0.00020905074544308634
epoch: 600, acc: 1.0, loss: 0.00016578966518063863
epoch: 700, acc: 1.0, loss: 0.00013661246641968417
epoch: 800, acc: 1.0, loss: 0.00011570921075354717
epoch: 900, acc: 1.0, loss: 0.00010005494137938699
epoch: 1000, acc: 1.0, loss: 8.792701810608727e-05
epoch: 1100, acc: 1.0, loss: 7.827560588258657e-05
epoch: 1200, acc: 1.0, loss: 7.042628863398778e-05
epoch: 1300, acc: 1.0, loss: 6.392690493701519e-05
epoch: 1400, acc: 1.0, loss: 5.8463459422726613e-05
epoch: 1500, acc: 1.0, loss: 5.3811342496364776e-05
epoch: 1600, acc: 1.0, loss: 4.980587105283189e-05
epoch: 1700, acc: 1.0, loss: 4.632360571704212e-05
epoch: 1800, acc: 1.0, loss: 4.327036479869193e-05
epoch: 1900, acc: 1.0, l